### ISSUE TITLE
Navigation buttons broke in v1.0.0

### ISSUE THREAD

**Issue by daniel-de-wit** [Ember-Swiper/ember-cli-swiper#104]
**Steps to reproduce:**

```
ember-cli: 3.1.3
node: 9.11.1
os: darwin x64
```

`ember new swiper-test` & `cd swiper-test`

`ember install ember-cli-swiper`

Replace application.hbs with:
```
{{#swiper-container navigation=true}}
  {{#swiper-slide}}Slide 1{{/swiper-slide}}
  {{#swiper-slide}}Slide 2{{/swiper-slide}}
  {{#swiper-slide}}Slide 3{{/swiper-slide}}
  {{#swiper-slide}}Slide 4{{/swiper-slide}}
  {{#swiper-slide}}Slide 5{{/swiper-slide}}
{{/swiper-container}}
```

`ember s`

**How it works**

Downgrade to `"ember-cli-swiper": "0.7.4",`
`yarn`
`ember s`

**Comment by Matt-Jensen** [comment]
Please try latest and let me know if you have any issues.

**Comment by daniel-de-wit** [comment]
Thank you! Everything is working as expected 👍
