### ISSUE TITLE
Issues with actions dying when loop is enabled

### ISSUE THREAD

**Issue by cwhittl** [Ember-Swiper/ember-cli-swiper#107]
We've seen this a few times, when the slides have click-able items on them when the loop is enabled anything on the looped slides can't be clicked.  It's like it does a deep clone but not deep enough.

Anyone seen this or have a fix for it?

**Comment by Matt-Jensen** [comment]
So I understand the issue fully, you've added a slider that loops from the first to the last slide.  In those slides (first and/or last) you've added click event listeners to child elements.  Swiper is cloning the elements (in order to loop) however the event listeners are not also cloned.

If that sounds correct, have you tried using event delegation on an element that is parent to the swiper container?

**Comment by cwhittl** [comment]
That is correct, it's been one of those days and I'm not following your suggestion. Can you elaborate?


On Wed, Jul 18, 2018 at 9:36am, Matt-Jensen < notifications@github.com [notifications@github.com] > wrote:
So I understand the issue fully, you've added a slider that loops from the first to the last slide. In those slides (first and/or last) you've added click event listeners to child elements. Swiper is cloning the elements (in order to loop) however the event listeners are not also cloned.

If that sounds correct, have you tried using event delegation on an element that is parent to the swiper container?

**Comment by Matt-Jensen** [comment]
What I'm suggesting is something like this in your HTML:
```
<event-delegator> {{!-- now handle events --}}
    {{#swiper-container}}
            {{swiper-slide}} {{!-- removed events--}}
    {{/swiper-container}}
</event-delegator>
```

Google can answer the rest for you in terms of implementing event delegation.

**Comment by Matt-Jensen** [comment]
Sure, that and the Swiper lib is only cloning the html elements _not their event bindings_ when you enable looping.  You can avoid that issue and possibly improve performance by using event delegation.  

Please reopen if you find a bug here.
