### ISSUE TITLE
Prev-Next Navigation as Action Outside of {{#swiper-container}}

### ISSUE THREAD

**Issue by ChristopherJohnson25** [Ember-Swiper/ember-cli-swiper#109]
Is there a way to do this? I'd like to have my own custom navigation elements outside of the swiper element. Tracked through the docs and couldn't find anything. Any help appreciated! Thanks.

**Comment by Matt-Jensen** [comment]
Of course, checkout the "2 way binded index" example in the demo: https://ember-swiper.github.io/ember-cli-swiper/

**Comment by Matt-Jensen** [comment]
I think you would just generally move your buttons and bindings up, out of that component, into a more appropriate context (maybe into the template?).  The demo does exactly this.
