### ISSUE TITLE
Swiper slides randomly stop working

### ISSUE THREAD

**Issue by rofoto** [Ember-Swiper/ember-cli-swiper#112]
Hi, 

    I am currently working on an ember app and while using swiper I can make the slides and they will work, but at ( seemingly ) random points during making changes to the scss It will stop scrolling, reverting to code that was working doesn't fix it and I have to stop the ember server and close my editor ( VS Code ) then revert the changes for it to work again. 

Any help would be great. 

Thanks so much

**Comment by Matt-Jensen** [comment]
@rofoto Thanks for taking the time to address this.

Would you be able to document your bug report using the [format described here](https://marker.io/blog/bug-report-template/#github).  Additionally any example code or even an example repo is always appreciated by maintainers.
