### ISSUE TITLE
forceUpdate not resetting current slide index

### ISSUE THREAD

**Issue by BHuys** [Ember-Swiper/ember-cli-swiper#113]
I'm using a slider to show dynamic data, the amount of slides changes. When I use forceUpdate after I get my new data into my slider, the index of the currentslide isn't reset to 0. Is there a way to achieve this behaviour?

options:

```
let sliderOptions = {
            autoplay: {
                delay: this.IMAGEINTERVAL * 1000
            },
            speed: this.SLIDEINTERVAL * 1000
        };
        this.set('sliderOptions', sliderOptions);
```
change data:
```
this.set('activeImages', this.selectOutputCollectionImages());
            if(this.get('outputSlideshow')) {
                later(() => {
                    this.get('outputSlideshow').forceUpdate();
                }, 0);
            }
```
template:
```
{{#swiper-container registerAs=outputSlideshow options=sliderOptions}}
                        {{#each activeImages as |aI|}}
                        {{#swiper-slide}}<img src="{{aI}}">{{/swiper-slide}}
                        {{/each}}
                    {{/swiper-container}}
```

**Comment by edeis53** [comment]
@BHuys did you solve this?

**Comment by BHuys** [comment]
@edeis53 I didn't, just wrote my own carousel for this project because there was no reaction to my issue.

**Comment by Matt-Jensen** [comment]
I'm sorry for the lack of response.  I guess I'm just confused why you expect `forceUpdate` to reset the index of the slider?  Why don't you just directly set the slider index back to zero?

Also `forceUpdate` is code smell, I'd avoid using it unless you absolutely need it.
