### ISSUE TITLE
currentSlide does not update when removing the current viewing item

### ISSUE THREAD

**Issue by rodrigoyoshida** [Ember-Swiper/ember-cli-swiper#116]
If I have the following case and I am viewing the last item, when removing it from the array the ember-swiper sends me to the previous (in this case, the first) image as expected, but it does not update the currentSlide property, causing me erros if I need it to get other info about the current viewing item which does not exists anymore.

``` javascript
this.set('photos', [
  'photo1.jpg', 
  'photo2.jpg'
]);
```

``` hbs
{{
  #swiper-container
  currentSlide=currentSlide
  navigation=true
  updateFor=photos
}}
  {{#each photos as |photo|}}
    {{#swiper-slide}}
      <img src="{{photo}}">
    {{/swiper-slide}}
  {{/each}}
{{/swiper-container}}
```

**Comment by Matt-Jensen** [comment]
I'm sorry to hear about this, would you be able to do a PR with a failing integration test for this edge case?

**Comment by rodrigoyoshida** [comment]
Sorry for the taking so long to answer.

I think I found where the issue is, the addon watches for the 'slideChangeTransitionEnd' event to fire the _slideChanged method, but this event only fires when the transition animation ends. 

This animation does not happen when deleting the last item, it goes back to the previous item without animating. We can use the 'slideChange' event instead, but that would not work when loop is set to true because it relies on the DOM to get the index, the 'slideChange' event is too early and it would get the old index. 

As a temporary fix I created a conditional to use the correct event for each case. I created a fork and a PR with the changes. I know I need to create a passing test for this case, but I think it would be useful to create this PR to start the discussion about it, because the way I solved it might not be the best solution.

**Comment by rodrigoyoshida** [comment]
This is the PR 

https://github.com/Ember-Swiper/ember-cli-swiper/pull/119

**Comment by Matt-Jensen** [comment]
Thanks for figuring this out! Definitely sounds like an annoying bug to nail down.

While I have nothing against your approach, I'd like to weight the pros and cons of just listening to both events and checking to see if any Swiper updates are necessary.

**Comment by rodrigoyoshida** [comment]
Ok! Tell me if I can help with anything.

**Comment by Matt-Jensen** [comment]
An Integration test would be welcome.  No matter what approach we take we can't merge without one.
