### ISSUE TITLE
Having trouble with slidesPerView: "auto"

### ISSUE THREAD

**Issue by madelio** [Ember-Swiper/ember-cli-swiper#117]
```
my component.hbs
{{#swiper-container slidesPerView="auto"}}
     {{#swiper-slide}}Slide 1{{/swiper-slide}}
     {{#swiper-slide}}Slide 2{{/swiper-slide}}
     {{#swiper-slide}}Slide 3{{/swiper-slide}}
     {{#swiper-slide}}Slide 4{{/swiper-slide}}
     {{#swiper-slide}}Slide 5{{/swiper-slide}}
{{/swiper-container}}
```
However nothing is changing, and it's still showing just one slide. What I want is for as many slides to display that will fit inside my container. 

Is there anything that I'm missing? Please and Thank you!

**Comment by Matt-Jensen** [comment]
Can you describe in more detail what you mean by "nothing is changing"?

Also can you confirm that your styles are not causing the issue?  [Here's Swipers Demo](https://github.com/nolimits4web/Swiper/blob/master/demos/120-slides-per-view-auto.html) of `slidesPerView: auto`.

Screenshots are always welcome for debugging issues like this as well.

**Comment by madelio** [comment]
Hi Matt! Thank you for your quick response!

By nothing is changing I mean that even if I have `slidesPerView="auto"` set or not, there is no difference and I'm seeing only one slide per view.

However after taking a look at the swipers demo, I see that they set a width for `.swiper-slide`. After setting my `.swiper-slide` width to auto, it's now behaving as I expect. 
![image](https://user-images.githubusercontent.com/18036294/56978852-4fead080-6b2d-11e9-989f-89cc2b1da4ad.png)

However, I'm running into a new issue now when I hit the right navigation or swipe to the left it will continuously let me swiping even if there are no more items on the screen.
![image](https://user-images.githubusercontent.com/18036294/56979230-22525700-6b2e-11e9-8559-f5823a9d15c6.png)

Please let me know if there are any other details I can provide. Thanks again!

**Comment by Matt-Jensen** [comment]
Sounds like a totally new issue to me.  If you can show me an example of a raw Swiper implementation working differently than an identically configured Ember swiper implementation I'd be happy to help you debug this further.

At the moment I can't really tell if it's a configuration flaw, styling issue, bug with Swiper.js, or a bug with this project.

If you can provide an example that will tell us definitively what the issue is we can move forward from there.

**Comment by Matt-Jensen** [comment]
Please reopen if you'd like further help

**Comment by madelio** [comment]
Just wanted to share what I found. So in my html, I was using `sr-only` with spans in my buttons. And `watchOverflow` was calculating the width including the sr-only spans before they were hidden causing the width to be super long. Switching to `aria-label` fixed my issue.
