### ISSUE TITLE
DEPRECATION: @component:swiper-container::ember404>#options computed property was just overriden

### ISSUE THREAD

**Issue by Driezzz** [Ember-Swiper/ember-cli-swiper#118]
The following deprecation warning occurs since ember-cli 3.9. 

> The @component:swiper-container::**#options** computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually.

and

> The @component:swiper-container::**#events** computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually.

The warning mentions the following url: https://deprecations.emberjs.com/v3.x/#toc_computed-property-override

**Comment by Matt-Jensen** [comment]
Yeah looks like we'll either need to define setters for those computed properties or replace them when primitive values
