### ISSUE TITLE
Custom Pagination and Navigation

### ISSUE THREAD

**Issue by natotthomer** [Ember-Swiper/ember-cli-swiper#135]
Just stumbled upon this project but I'm not sure how I'd make custom navigation and pagination elements outside of just providing some custom classes for those elements (which I'm also not entirely sure how to do). Can you provide some documentation for those features?

Specifically I'm trying to do something like this:

- pagination buttons on the bottom (that part I've already figured out). But the tricky part I'm trying to make work is this: you won't necessarily see all the pagination buttons at a given time (since there might be dozens of slides and that many buttons would be overwhelming). I'd like to control how many buttons you see and how they taper off (like on Instagram where the buttons get smaller as they get farther from the currently selected page button).
- I want to make the next/previous buttons the full height of the card in order to be easier to click.

See the image below for an example (the red rectangle is not part of the design, it's just representing the clickable area of the `prev` button)
<img width="578" alt="Screen Shot 2021-03-01 at 5 10 13 PM" src="https://user-images.githubusercontent.com/17552236/109565885-17153d00-7ab1-11eb-82c2-ec68a109dc4f.png">

**Comment by Matt-Jensen** [comment]
Hey thanks for making this issue.  I'm not sure this addon currently supports Swiper's custom navs (could be wrong).  I welcome you to make a PR and I'll get it merged.  Otherwise you'll need to fork to get the functionality you need.

**Comment by natotthomer** [comment]
I was able to get most of what I needed via Swiper's API. The rest I hacked together with some careful CSS selectors. Thanks!
