### ISSUE TITLE
more maintainers needed 👀

### ISSUE THREAD

**Issue by Suven** [Ember-Swiper/ember-cli-swiper#65]
Hi,

unfortunally my job/daily work as shifted in an unpredicted way over the last few months.

In the past I was able to maintain this package partly in my spare time and partly in a work-related manner.

As I am currently not working with ember anymore, it's hard for me to keep track / review PRs.

Because of that I am looking for people who would like to be core-contributors of this project.

You will get rights to:
- review and merge PRs
- make new releases on npm

You need to:
- be on track with current developments in EmberJS
- ideally using this plugin actively by yourself

**Comment by Matt-Jensen** [comment]
I can help

**Comment by Matt-Jensen** [comment]
@Suven I don't have permission to make new releases on npm.

**Comment by xtagon** [comment]
I am using this plugin actively and more than willing to contribute.

**Comment by Matt-Jensen** [comment]
@xtagon @Suven we need a plan to ship updated code and bugfixes to users of this project via npm.  Organizationally we are not doing a good job of this and causing unnecessary frustration and confusion for our users.

I propose that one of the 2 happen:
- We create a new Github organization that owns the namespace `ember-cli-swiper`, where maintainers have permission to commit and publish to npm. Here Suven transfers ownership of the project while maintaining his status as author of the project.
- I clone this repo into the new Github org and claim a new Ember addon namespace, which will compete with this project.  This is by far the least desirable outcome for our community, but one that is necessary to ship updated code to our users.

The organization's name is: [Ember-Swiper](https://github.com/Ember-Swiper).  Please ping me if you'd like to be a member/collaborator there.  In one week (12/8/17) I hope we can agree on the better outcome for everyone.

**Comment by 0xadada** [comment]
@Matt-Jensen i'm for it, add me.

**Comment by Matt-Jensen** [comment]
@0xadada if Suven agrees to transfer the project we could rename it, if he doesn't I don't want to create more confusion by using the same name.

**Comment by 0xadada** [comment]
@Matt-Jensen sounds good.

**Comment by xtagon** [comment]
@Matt-Jensen Sounds good. Thank you for taking action.

May I be added to the new org?

**Comment by Suven** [comment]
Hey all!

I am too busy to activly maintain this repo, but don't want to push changes to npm without reviewing them either.

I would be okay with transfering the repo to the org. @Matt-Jensen

**Comment by 0xadada** [comment]
@Suven @Matt-Jensen lets add @Suven to the org so he can continue to review/approve PRs, and he can transfer ownership to the org himself.

**Comment by Matt-Jensen** [comment]
Fully support that! Looks like @Suven has already been invited and I've invited @xtagon as an admin as well.

Suven once you transfer this repo to the Github org would you be alright adding read-write access to your npm module?  I've created an npm org (ember-cli-swiper) so you can do that with a single command and all you would have to do is run:

`npm access grant read-write ember-cli-swiper:developers ember-cli-swiper`

You would no longer have to even manage publish access from that point either.  Sound good?

**Comment by Suven** [comment]
Sounds good to me. I think my invitation has been revoked though

**Comment by Matt-Jensen** [comment]
Resent your invite.

If everyone could give me their npm usernames (except Suven, which I have) that would be great.

**Comment by 0xadada** [comment]
@Matt-Jensen NPM: @0xadada

**Comment by Suven** [comment]
Did the transfer + npm-change. 

Could take a couple of minutes to complete processing.

**Comment by Matt-Jensen** [comment]
I see it! As discussed I've changed the Github org name to: `ember-cli-swiper`

That's why I love the Ember community! Thank you @Suven for ensuring that this project has the maintainers necessary to make it a success moving forward. We all owe you a big thank you.

**Comment by xtagon** [comment]
Thanks everyone!

@Matt-Jensen I don't think I need NPM publish access at this point but I absolutely look forward to contributing to the development.
