### ISSUE TITLE
Pagination & navigation in v0.7.0

### ISSUE THREAD

**Issue by patric-eberle** [Ember-Swiper/ember-cli-swiper#79]
The `swiper-container.hbs` only en-/disables pagination and navigation if the two properties are defined as attributes when inserting the component.

```
Controller.extend({
  galleryOptions: { navigation: true, pagination: true }
});
```

```
{{#swiper-container
  options=galleryOptions
  navigation=true
  pagination=true
}}
  This works
{{/swiper-container}}
```

```
{{#swiper-container
  options=galleryOptions
}}
  This doesn't work (pagination/navigation are not displayed, because they are set in options.x)
{{/swiper-container}}
```

**Comment by Matt-Jensen** [comment]
The first swiper container works because the `navigation` and `pagination` take precedence over `options.{navigation, pagination}`, so this likely is not telling us anything about the consumption of `options`.

> This doesn't work (pagination/navigation are not displayed, because they are set in options.x)
Does this mean that `navigation` and `pagination` are not defined on `galleryOptions`?

**Comment by Matt-Jensen** [comment]
@patric-eberle found the issue: https://github.com/Ember-Swiper/ember-cli-swiper/blob/af10d0c6878096eb2e42aeeba08c5c3ff8f973d8/addon/templates/components/swiper-container.hbs#L9
