### ISSUE TITLE
Glitch Issue

### ISSUE THREAD

**Issue by gullocean** [Ember-Swiper/ember-cli-swiper#82]
I love this package very much, but just wondering about glitch issue on mobile.
I have inserted the slider section into iFrame tag for my needs. but there is a glitch on mobile.  All slider images are flickering. could you please help me for this case? For more details, you can check this URL on mobile.
Thanks

**Comment by Matt-Jensen** [comment]
Hey @gullocean,

Can you make an example repo of this issue and provide a url to it so we can have a better idea of what you're talking about and could debug the problem?
