### ISSUE TITLE
does not update on adding or removing slides

### ISSUE THREAD

**Issue by jelhan** [Ember-Swiper/ember-cli-swiper#90]
If you add or remove slides, swiper shows some issues. If more slides are removed than added, you end up with an empty slide. If more slides are added than removed, the last one is not accessible. You find an ember-twiddle demonstrating the issue here: https://ember-twiddle.com/dcc18bd7d53c6979320b991db79d1bca?fileTreeShown=false&numColumns=0

**Comment by jelhan** [comment]
Everything is working as expected if I pass `observer=true` option to `{{swiper-container}}`. Sorry for the noice.

**Comment by edeis53** [comment]
@jelhan can you share your implementation?

 I'm sending a filtered array of 5 slides only, after the user increments or decrements the current slide, I repopulate the filtered model (add a new slide at the end, and remove one from the beginng). But swiper seems to change the current slide index to zero when I do so, and I can't seem to correct it.

**Comment by jelhan** [comment]
@edeis53 It's a long time ago but if I take the twiddle in my first post and change line 7 in `templates/application.hbs` from `{{#swiper-container}}` to `{{#swiper-container observer=true}}` it's working as expected. Without that change I could reproduce the issues as described in the twiddle. This feature is described [in API docs](http://idangero.us/swiper/api/).

IMO it's not very intuitive in an ember world that observing property changes is an opt-in but `observer` defaults to `false`. And in that case swiper does not support to _"change its style (like hide/show) or modify its child elements"_.
