### ISSUE TITLE
Properties on slider container not updating when computed property changes

### ISSUE THREAD

**Issue by mattmcginnis** [Ember-Swiper/ember-cli-swiper#91]
I'm trying to enable/disable swiping & clicking next/prev using computed properties but it does not work.  Setting the appropriate properties to booleans works but they cannot be changed.

For example, this correctly disables swiping and clicking next/prev:

```
{{#swiper-container
  noSwiping=true
  noSwipingClass='swiper-slide'
  allowSwipeToPrev=false
  allowSwipeToNext=false
}}
```
Unfortunately, this does not allow you to enable swiping and clicking next/prev.  Ideally, you could use a computed property to enable/disable like this:

component:
```
swipingEnabled: true,
swipingDisabled: Ember.computed.not('swipingEnabled')
```

template:
```
{{#swiper-container
  noSwiping=swipingDisabled
  noSwipingClass='swiper-slide'
  allowSwipeToPrev=swipingEnabled
  allowSwipeToNext=swipingEnabled
}}
```

Unfortunately, this does not work.  Only the initial value of swipingEnabled or swipingDisabled is respected. If you toggle swipingEnabled, it does not toggle the functionality.

I've also tried the following:
```
{{#swiper-container
  noSwiping=swipingDisabled
  noSwipingClass='swiper-slide'
  allowSwipeToPrev=swipingEnabled
  allowSwipeToNext=swipingEnabled
  updateFor=swipingEnabled
  registerAs=superDuperSwiper
}}
```
    toggleSliderEnabled() {
      this.toggleProperty('swipingEnabled');
      this.get('superDuperSwiper').forceUpdate();
    }
```

**Comment by Matt-Jensen** [comment]
Help me to understand your use case, because it seems to me that `noSwiping` and `allowSwipeToPrev/allowSwipeToNext` options are mutually exclusive as they naturally would conflict.  Is there a situation you _need_ to use both?

I guess what I'm getting at is that it would be easier for me to debug the issue once your example eliminates the possibility of conflicts in the settings.

**Comment by mattmcginnis** [comment]
Maybe I don't understand how it's intended to work.  Which if any of these scenarios are valid?

#1
```
{{#swiper-container
  noSwiping=true
  noSwipingClass='swiper-slide'
  allowSwipeToPrev=false
  allowSwipeToNext=false
}}
```

#2 
```
{{#swiper-container
  noSwiping=false
  noSwipingClass=null
  allowSwipeToPrev=true
  allowSwipeToNext=true
}}
```
#3 
```
{{#swiper-container
  noSwiping=false
  noSwipingClass=null
  allowSwipeToPrev=false
  allowSwipeToNext=true
}}
```

**Comment by Matt-Jensen** [comment]
1 and 2 just look redundant to me.  Far simpler to just do `{{swiper-container noSwiping=true}}` and `{{swiper-container noSwiping=false}}` respectively.

3. `noSwiping=false` conflicts with `allowSwipeToNext=false` rather the component should be defined as:
```hbs
{{#swiper-container
  allowSwipeToPrev=false
  allowSwipeToNext=true
}}
```
Since you need more fine grained control than `noSwiping` provides.

**Comment by mattmcginnis** [comment]
So then this scenario is not possible, correct?

Dynamically switch between these two conditions:

1)
noSwiping is true only for "class1"
allowSwipeToNext is true (for classes other than "class1")
allowSwipeToPrev is false for all classes

2)
noSwiping is false
allowSwipeToNext is true
allowSwipeToPrev is false

**Comment by Matt-Jensen** [comment]
While it's entirely _possible_ to provide all those options together, all I'm saying is it doesn't make any sense to me why someone would do so when you could just do:

```hbs
{{!-- Disabled --}}
{{swiper-container  allowSwipeToPrev=false  allowSwipeToNext=false}}
```

```hbs
{{!-- Enabled --}}
{{swiper-container  allowSwipeToPrev=true  allowSwipeToNext=true}}
```

Whereas when you do:
```hbs
{{swiper-container noSwiping=true  allowSwipeToPrev=true  allowSwipeToNext=true}}
```
You're basically saying: "The slider can swipe left and right... and swiping is disabled" those 2 instructions are obviously in conflict and which instruction wins is 100% up to how Swiper.js implements it and has nothing to do with this addon.  This why I want us to stop using them together so we can get to the bug you've reported: that computed properties are not updating the container.

**Comment by mattmcginnis** [comment]
What I thought I could say is "Allow swiping for all classes except X". It seems this is not true.

**Comment by Matt-Jensen** [comment]
Fair enough, I'm going to close this for now.  If you find that computed properties are not updating the `swiper-container` please feel free to reopen the issue.
