### ISSUE TITLE
Set wrapper class without extending the addon?

### ISSUE THREAD

**Issue by lougreenwood** [Ember-Swiper/ember-cli-swiper#94]
Is it possible to set the wrapper class without having to extend the addon?

<img width="619" alt="screen shot 2018-03-20 at 22 14 21" src="https://user-images.githubusercontent.com/12051736/37685645-18ba996e-2c8c-11e8-8160-f509498daad7.png">

**Comment by Matt-Jensen** [comment]
What's your use case for this?
